In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataSet's/house.csv")
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [3]:
df.head(5)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council

In [16]:
#filter1 = df.loc[(df['Rooms'] == 3) & (df['Type'] == 'h') & (df['Price'] <= 500000)]
filter1 = df.loc[(df['Rooms'] == 3) & (df['Type'] == 'h') & (df['Price'] >= 500000)]
filter1

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,SP,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63011,Doveton,12 Scarlet Dr,3,h,595000.0,PI,REMAX,31/03/2018,3177,South-Eastern Metropolitan,3533,28.8,Casey City Council
63017,Preston,229 Murray Rd,3,h,808000.0,S,RW,31/03/2018,3072,Northern Metropolitan,14577,8.4,Darebin City Council
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council

In [25]:
# busca por coluna e palavra especifica dentro dessa coluna
#filter2 = df.loc[df['Address'].str.contains('Turner St|Turner Rd')] 
## Ignorar as letras maisculas e minusculas:
import re # Importar o Regular Expressions para que o flags=re.I funcione
filter2 = df.loc[df['Address'].str.contains('Turner St|Turner Rd', flags=re.I)] 
filter2

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2859,Malvern East,24 Turner St,6,h,4700000.0,S,RT,3/03/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
4723,Highett,48 Turner Rd,2,h,832000.0,S,Buxton,3/09/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
4987,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
7501,Highett,28 Turner Rd,3,h,NaN,PI,Nick,4/08/2018,3190,Southern Metropolitan,4794,16.0,Bayside City Council
9647,Abbotsford,53 Turner St,2,h,NaN,S,Biggin,6/08/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
9648,Abbotsford,99 Turner St,2,h,NaN,S,Collins,6/08/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
14012,Berwick,4 Turner St,5,h,536000.0,S,O'Brien,8/04/2017,3806,Eastern Victoria,17093,35.2,Casey City Council
14745,Westmeadows,16 Turner St,3,h,NaN,SN,Stockdale,8/04/2017,3049,Northern Metropolitan,2474,16.5,Hume City Council
18960,Moonee Ponds,3/16 Turner St,2,u,550000.0,VB,Woodards,10/09/2016,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
19148,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10/12/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
19609,Highett,2/20 Turner Rd,2,u,730000.0,SP,Buxton,10/12/2016,3190,Southern Metropolitan,4794,16.0,Bayside City Council
20043,Westmeadows,14 Turner St,3,h,586000.0,S,Stockdale,10/12/2016,3049,Northern Metropolitan,2474,16.5,Hume City Council
20717,Langwarrin,49 Turner Rd,4,h,NaN,PI,UFirst,11/08/2018,3910,Eastern Victoria,8743,41.0,Frankston City Council
25081,Moonee Ponds,15/3 Turner St,3,t,732000.0,S,Nelson,13/10/2018,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
26305,Abbotsford,2 Turner St,3,h,1620000.0,S,Biggin,14/07/2018,3067,Northern Metropolitan,4019,3.0,Yarra City Council
29650,Briar Hill,10 Turner St,2,h,812000.0,S,Darren,16/06/2018,3088,Eastern Metropolitan,1390,16.1,Banyule City Council
36217,Westmeadows,25 Turner St,4,h,685000.0,S,Jason,18/06/2016,3049,Northern Metropolitan,2474,16.5,Hume City Council
39873,Highett,3/6 Turner Rd,3,u,NaN,PI,Buxton,20/05/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
41985,Highett,1/6 Turner Rd,4,h,921000.0,S,Buxton,22/04/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
42537,Malvern East,16 Turner St,4,h,NaN,S,Marshall,22/05/2016,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
45597,Highett,3/15 Turner Rd,2,u,770000.0,S,McGrath,23/09/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
47333,Malvern East,27 Turner St,2,h,1040000.0,S,Jellis,24/02/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
47843,Berwick,6 Turner St,4,h,1400000.0,VB,Peake,24/03/2018,3806,Eastern Victoria,17093,35.2,Casey City Council
49480,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,3067,Northern Metropolitan,4019,3.0,Yarra City Council
49890,Moonee Ponds,4/6 Turner St,2,u,600000.0,S,Woodards,24/09/2016,3039,Western Metropolitan,6232,6.2,Moonee Valley City Council
50254,Briar Hill,7 Turner St,4,h,1100000.0,S,Jellis,25/02/2017,3088,Eastern Metropolitan,1390,16.1,Banyule City Council
51364,Malvern East,29 Turner St,2,h,1010000.0,SP,Jellis,25/08/2018,3145,Southern Metropolitan,8801,8.4,Stonnington City Council
53753,Highett,2/4 Turner Rd,2,u,680500.0,S,Ray,26/08/2017,3190,Southern Metropolitan,4794,16.0,Bayside City Council
57940,Abbotsford,210/125 Turner St,2,u,760000.0,S,Nelson,28/07/2018,3067,Northern Metropolitan,4019,3.0,Yarra City Council
57978,Berwick,5 Turner St,4,h,940000.0,SP,Ray,28/07/2018,3806,Eastern Victoria,17093,35.2,Casey City Council
58707,Highett,22 Turner Rd,3,h,1150000.0,SP,Buxton,28/08/2016,3190,Southern Metropolitan,4794,16.0,Bayside City Council

In [29]:
## Using Regular expressions with conditions
# specific street and price < 
filter3 = df.loc[(df['Address'].str.contains('^59', flags=re.I)) & (df['Price'] <= 500000)] 
# para nÃ£o aparecer nÃºmeros alem do 59 colocamos o ^ para dizer que inicie com 59
filter3

# Posso utilizar o | (ou)
# filter3 = df.loc[(df['Address'].str.contains('^59', flags=re.I)) | (df['Price'] <= 500000)]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
2220,Wallan,59 William St,3,h,424000.0,S,Ruralco,2/06/2018,3756,Northern Victoria,3988,44.2,Mitchell Shire Council
9096,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,6/01/2018,3429,Western Metropolitan,14092,31.7,Hume City Council
13089,Sunshine West,59 Felstead Av,3,h,465000.0,S,Bells,7/11/2016,3020,Western Metropolitan,6763,10.5,Brimbank City Council
13840,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,8/01/2018,3429,Western Metropolitan,14092,31.7,Hume City Council
19616,Hoppers Crossing,59 Aitken Av,3,h,421600.0,SP,Barry,10/12/2016,3029,Western Metropolitan,13830,18.4,Wyndham City Council
19623,Hoppers Crossing,59 Mossfiel Dr,3,h,453000.0,S,Triwest,10/12/2016,3029,Western Metropolitan,13830,18.4,Wyndham City Council
30441,Thomastown,59 Darebin Dr,3,h,478500.0,S,hockingstuart,16/07/2016,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
31889,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,16/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council
46682,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,23/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council
62903,Sunbury,59 Davenport Dr,3,h,499500.0,S,Barry,30/12/2017,3429,Western Metropolitan,14092,31.7,Hume City Council

In [32]:
## modifying data frame
#Lemos o data frame
df = pd.read_csv("dataSet's/house.csv")
#e primeiro vamos listar um vendedor em SellerG
df.loc[df['SellerG'] == 'Nelson', 'SellerG'] = 'Ronald'
df

In [35]:
df.loc[df['SellerG'] == 'Ronald', ['Method']] = 'Pending'
df
# Trocando multiplos
df.loc[df['SellerG'] == 'Ronald', ['Method', 'Type']] = 'Pending'
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,Pending,1420000.0,Pending,Ronald,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,Pending,670000.0,Pending,Ronald,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [2]:
# Nova aula
import pandas as pd
import re

df = pd.read_csv("dataSet's/house.csv")

In [5]:
df.groupby(['SellerG']).mean('Rooms')

                 Rooms         Price     Postcode  Propertycount   Distance
SellerG
@Realty       3.629630  7.489286e+05  3086.814815    8510.888889  15.948148
A             3.000000  7.265000e+05  3047.888889    4412.000000  13.533333
AIME          4.000000  9.800000e+05  3147.000000    2894.000000  10.200000
ASL           3.400000  1.103750e+06  3104.900000    9702.000000  14.820000
Abercromby's  3.220588  2.152905e+06  3139.323529    8806.500000   5.152941
...                ...           ...          ...            ...        ...
iOne          3.000000  6.200000e+05  3013.000000    6543.000000   6.300000
iProperty     3.000000  8.200000e+05  3133.000000    4181.000000  17.200000
iSell         3.165354  7.200606e+05  3190.055118    7636.574803  22.168504
iTRAK         3.306667  7.343636e+05  3196.773333    6775.426667  24.645333
voglwalpole   3.250000  7.665000e+05  3134.500000    3507.000000  20.600000

[476 rows x 5 columns]

In [13]:
# primeiro eu agrupo os vendedores, com Sum somo os valores da coluna Price em ordem crescente
#por causa do ascending = False, e com o head coloco apenas os 10 primeiros
df.groupby(['SellerG']).sum('Price').sort_values('Rooms', ascending = False).head(10)

               Rooms         Price  Postcode  Propertycount  Distance
SellerG
Barry          22919  4.022899e+09  21405391       54662639  108662.2
Jellis         16948  5.301902e+09  17116422       42958979   47831.6
Ray            14961  2.953669e+09  14329293       41191735   76239.1
Nelson         13808  4.089097e+09  14489179       35455466   34410.5
hockingstuart  12635  3.174822e+09  13571171       36291698   53918.3
Buxton         10707  3.103258e+09  10669223       21365913   48190.6
Marshall        9437  3.337732e+09   8949613       22270034   20141.4
Fletchers       5402  1.384292e+09   5039345       10521475   21963.2
Biggin          4203  1.002292e+09   4783284       12904764   12250.2
Harcourts       4086  7.851802e+08   3877544       11905589   21653.0

In [16]:
#Soma todos os valores que ele consegue somar com o count()
df.groupby(['SellerG']).count().sort_values('Rooms', ascending = False).head(10)

,Suburb,Address,Rooms,Type,Price,Method,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
SellerG,,,,,,,,,,,,
Barry,6894,6894,6894,6894,4818,6894,6894,6894,6894,6894,6894,6894
Jellis,5499,5499,5499,5499,4088,5499,5499,5499,5499,5499,5499,5499
Nelson,4739,4739,4739,4739,4008,4739,4739,4739,4739,4739,4739,4739
Ray,4554,4554,4554,4554,3653,4554,4554,4554,4554,4554,4554,4554
hockingstuart,4332,4332,4332,4332,3465,4332,4332,4332,4332,4332,4332,4332
Buxton,3357,3357,3357,3357,2580,3357,3357,3357,3357,3357,3357,3357
Marshall,2844,2844,2844,2844,1721,2844,2844,2844,2844,2844,2844,2844
Fletchers,1612,1612,1612,1612,1160,1612,1612,1612,1612,1612,1612,1612
Biggin,1535,1535,1535,1535,1022,1535,1535,1535,1535,1535,1535,1535
Harcourts,1211,1211,1211,1211,912,1211,1211,1211,1211,1211,1211,1211

In [17]:
df.groupby(["SellerG"]).count()

,Suburb,Address,Rooms,Type,Price,Method,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
SellerG,,,,,,,,,,,,
@Realty,27,27,27,27,21,27,27,27,27,27,27,27
A,9,9,9,9,6,9,9,9,9,9,9,9
AIME,1,1,1,1,1,1,1,1,1,1,1,1
ASL,10,10,10,10,10,10,10,10,10,10,10,10
Abercromby's,68,68,68,68,42,68,68,68,68,68,68,68
...,...,...,...,...,...,...,...,...,...,...,...,...
iOne,1,1,1,1,1,1,1,1,1,1,1,1
iProperty,1,1,1,1,1,1,1,1,1,1,1,1
iSell,127,127,127,127,99,127,127,127,127,127,127,127
iTRAK,75,75,75,75,70,75,75,75,75,75,75,75
voglwalpole,4,4,4,4,2,4,4,4,4,4,4,4